In [2]:
l = [23245, 27, 546, 215, -1234]

In [3]:
l

[23245, 27, 546, 215, -1234]

In [4]:
import numpy as np #do this so I can use np instead of typing out numpy

In [8]:
a = np.array(l)

In [9]:
a

array([23245,    27,   546,   215, -1234])

In [10]:
b= np.array([12, 455, 63.3, True, "abc"]) #arrays cannot have differnet data types below was all converted to strings

In [11]:
print (b)

['12' '455' '63.3' 'True' 'abc']


In [13]:
l.pop() #press l. and tab you get a list of functions

-1234

In [14]:
l

[23245, 27, 546, 215]

In [16]:
a.mean() #press a. tab and arrays give you a much bigger list of functions

4559.8

In [19]:
c= np.array([12, 455, 63.3,])

In [28]:
a

array([23245,    27,   546,   215, -1234])

In [30]:
a[2:]

array([  546,   215, -1234])

In [31]:
a[2:4] #this is called slicing arrays however unlike a list we are not creating another copy of the array

array([546, 215])

In [32]:
b= a[2:4]

In [33]:
b

array([546, 215])

In [34]:
b[0]

546

In [35]:
b[:]=111 #changing the value here actually changed the value in the original array 'a'

In [36]:
b

array([111, 111])

In [37]:
a

array([23245,    27,   111,   111, -1234])

In [38]:
c = a.copy() #when you copy an array you are telling the computer you are making a new array

In [39]:
c

array([23245,    27,   111,   111, -1234])

In [40]:
c[0]=0

In [41]:
c

array([    0,    27,   111,   111, -1234])

In [42]:
a

array([23245,    27,   111,   111, -1234])